---
- name: "Running task on Workers, Copying telegraf.conf"
  template: 
    src: telegraf_th_cluster_workers.conf
    dest: /etc/telegraf/telegraf.conf 
    owner: telegraf 
    group: telegraf
    mode: 0775 
    backup: yes
  when:
      inventory_hostname in groups['workers']