---
- import_tasks: temp_directory_create.yml
- import_tasks: add_proxy_to_yum.yml
- import_tasks: telegraf_transfer_rpm.yml
- import_tasks: telegraf_install_local.yml
- import_tasks: temp_directory_delete.yml
- import_tasks: telegraf_run_as root.yml
- import_tasks: daemon_reload.yml
- import_tasks: copy_k8s_to_cluster.yaml
- import_tasks: copy_conf_files_to_workers.yml
- import_tasks: remove_and_create_ssh_tunnel.yml
