---
- import_tasks: temp_directory_create.yml
- import_tasks: add_proxy_to_yum.yml
- import_tasks: xidel_untar_local.yml
- import_tasks: xidel_install_local.yml
- import_tasks: telegraf_transfer_rpm.yml
- import_tasks: telegraf_install_local.yml
- import_tasks: temp_directory_delete.yml
- import_tasks: telegraf_run_as root.yml
- import_tasks: daemon_reload.yml
- import_tasks: copy_th_kafka_scripts_files_to_master.yml
- import_tasks: remove_and_create_ssh_tunnel.yml