---
- include: temp_directory_create.yml
- include: add_proxy_to_yum.yml
- include: xidel_untar_local.yml
- include: xidel_install_local.yml
- include: telegraf_transfer_rpm.yml
- include: telegraf_install_local.yml
- include: temp_directory_delete.yml
- include: copy_th_kafka_scripts_files.yml
- include: remove_and_create_ssh_tunnel.yml