---
- name: "Transferring Telegraf RPM for CentOS/RHEL"
  copy:
    src: "{{ item }}"
    dest: /opt/TH_SCRAPPER/
  with_fileglob:
    - telegraf-*.rpm
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: "Transferring Telegraf .deb package for Ubuntu/Debian"
  copy:
    src: "{{ item }}"
    dest: /opt/TH_SCRAPPER/
  with_fileglob:
    - telegraf_1.19.2-1_amd64.deb
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'